- hosts: all
  become: yes
  vars:
    base_locale: LANG=ja_JP.UTF-8
    base_timezone: Asia/Tokyo
  tasks:
    - name: ロケール設定
      command: localectl set-locale {{ base_locale }}

    - name: タイムゾーン設定
      command: timedatectl set-timezone {{ base_timezone }}

    - name: 基本パッケージをインストール
      yum: name={{ item }} state=present
      with_items:
        - vim
        - git
        - ntp

    - name: ntpdを起動、自動起動の有効化
      service: name=ntpd state=started enabled=yes

    - name: Apacheをインストール
      yum: name=httpd state=present
      tags:
        - apache

    - name: httpd.confテンプレートを転送
      template:
        src=files/apache/httpd.conf.j2
        dest=/etc/httpd/conf/httpd.conf
        owner=root
        group=root
        mode=0644
      tags:
        - apache
      notify:
        - Apacheを再起動

    - name: vhosts.confテンプレートを転送
      template:
        src=files/apache/vhosts.conf.j2
        dest=/etc/httpd/conf.d/vhosts.conf
        owner=root
        group=root
        mode=0644
      tags:
        - apache
      notify:
        - Apacheを再起動

    - name: Apacheを起動、自動起動を有効化
      service: name=httpd state=started enabled=yes
      tags:
        - apache

    - name: EPELリポジトリをインストール
      yum: name=epel-release state=present
      tags:
        - php

    - name: Remiリポジトリがインストール済か
      stat: path=/etc/yum.repos.d/remi-php70.repo
      register: remi_release_status
      tags:
        - php

    - debug: var=remi_release_status

    - name: Remiリポジトリをインストール
      yum: name="http://rpms.remirepo.net/enterprise/remi-release-7.rpm"
      when: remi_release_status.stat.exists == false
      tags:
        - php

    - name: PHP7.0をインストール
      yum: name={{ item }} state=present enablerepo=remi-php70
      with_items:
        - php
        - php-cli
        - php-process
        - php-pdo
        - php-pgsql
        - php-mbstring
        - php-mcrypt
        - php-devel
        - php-common
        - php-pear
        - php-opcache
        - php-json
        - php-pecl-memcached
        - php-pecl-zip
      notify:
        - Apacheを再起動
      tags:
        - php

  handlers:
    - name: Apacheを再起動
      service: name=httpd state=restarted
